site_name: Jetpack Compose 博物馆
repo_name: Jetpack Compose 博物馆
repo_url: https://github.com/Compose-Museum/Compose-Tutorial
site_url: https://github.com/Compose-Museum/Compose-Tutorial
edit_uri: tree/main/docs/

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  feature:
    - tabs: true
    - instant
    - header.autohide

nav:
  - 'Jetpack Compose':
    - '概述': index.md
    - '在开始之前': start.md
    - '基本组件':
        - 'Text': elements/text.md
        - 'Button': elements/button.md
        - 'Card': elements/card.md
        - 'Icon': elements/icon.md
        - 'Image': elements/image.md
        - 'IconButton': elements/iconbutton.md
    - '布局': 
        - 'Column': layout/column.md
        - 'Scaffold': layout/scaffold.md
    - '参数':
        - 'Modifier': parameters/modifier.md
    - '贡献': contributing.md
    - '资源': resources.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Compose-Museum/Compose-Tutorial/


markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: date