site_name: Jetpack Compose
site_url: https://docs.compose.net.cn/

assets: ../../../assets
code: ../../../code

repo_name: 'Jetpack Compose 博物馆'
repo_url: 'https://github.com/Compose-Museum/Compose-Tutorial'
edit_uri: 'tree/main/docs/'

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  features:
    - navigation.tabs
  font:
    code: Jetbrains Mono

nav:
  - 'Jetpack Compose':
    - '概述': index.md
    - '在开始之前': start.md
    - '快速入门': tutorial.md
    - '基本组件':
      - 'AlertDialog': elements/alertdialog.md
      - 'Button': elements/button.md
      - 'Card': elements/card.md
      - 'FloatingActionButton': elements/floatingactionbutton.md
      - 'Icon': elements/icon.md
      - 'Image': elements/image.md
      - 'IconButton': elements/iconbutton.md
      - 'Surface': elements/surface.md
      - 'Slider': elements/slider.md
      - 'Text': elements/text.md
      - 'TextField': elements/textfield.md
    - '布局组件':
      - 'BottomNavigation': layout/bottomnavigation.md
      - 'Column': layout/column.md
      - 'ModalBottomSheetLayout': layout/modalbottomsheetlayout.md
      - 'Row': layout/row.md
      - 'Spacer': layout/spacer.md
      - 'Scaffold': layout/scaffold.md
      - 'TopAppBar': layout/topappbar.md
      - '自定义布局': layout/custom_layout.md
      - '固有特性测量': layout/intrinsic.md
    - '设计':
      - '动画 (Animation)':
        - '概述': design/animation/overview.md
        - 'AnimationVisibility': design/animation/animationvisibility.md
        - 'Animate*State': design/animation/animatestate.md
        - 'Animatable': design/animation/animatable.md
        - 'UpdateTransition': design/animation/update_transition.md
      - '主题 (Theming)':
        - '概述': design/theme/overview.md
        - '初识 MaterialTheme': design/theme/meet_material_theme.md
        - '深入理解 MaterialTheme 与 CompositionLocal': design/theme/understanding_material_theme.md
        - '自定义你的主题方案': design/theme/custom_your_theme.md
      - '手势 (Gestures)':
        - '概述': design/gesture/overview.md
        - 'Draggable拖动': design/gesture/draggable.md
        - 'Swipeable滑动': design/gesture/swipeable.md
        - 'Transformer双指拖动、缩放与旋转': design/gesture/transformer.md
        - 'NestedScroll嵌套滑动': design/gesture/nested_scroll.md
        - '自定义触摸反馈': design/gesture/custom_gesture.md
      - '列表 (Lists)':
        - '概述': design/lists/overview.md
        - '列表点击事件': design/lists/list_item_click.md
      - '绘制 (Graphics)': design/draw/custom_draw.md
    - '关于 Modifier':
      - '概述': modifier/overview.md
      - '方法介绍': modifier/introduction.md
    - '技术原理':
      - '了解Compose的重组作用域': principle/recomposition_scope.md
      - '透过Snapshot看重组': principle/snapshot.md
      - 'Compose运行原理与GapBuffer': principle/gap_buffer.md
      - '重组的工作流程': principle/recompose_working_principle.md
      - '图解Modifier': principle/modifier_structure.md
    - '架构':
      - 'Compose架构如何选？MVP,MVVM,MVI': architecture/architecture_for_compose.md
      - '在 Compose 中使用 Jetpack 组件库': architecture/use_jetpack_in_compose.md
    - '代码实验室': codelabs.md
    - '资源': resources.md
    - '版本更新迭代内容与介绍': version.md
    - '关于贡献': contributing.md
  - '第三方组件':
    - 'Accompanist':
      - '概述': third-party-component/accompanist/overview.md
      - 'Coil': third-party-component/accompanist/coil.md
      - 'Glide': third-party-component/accompanist/glide.md
      - 'Insets': third-party-component/accompanist/insets.md
      - 'System UI Controller': third-party-component/accompanist/system_ui_controller.md
      - 'AppCompat Theme': third-party-component/accompanist/appcompat_theme.md
      - 'Pager layouts': third-party-component/accompanist/pager_layouts.md
      - 'Swipe Refresh': third-party-component/accompanist/swipe_refresh.md
      - 'Flow layouts': third-party-component/accompanist/flow_layouts.md
    - 'Compose版骨架屏': third-party-component/shimmer/compose_shimmer.md
    - 'Coil': third-party-component/coil/index.md
    - 'Compose版StateLayout': third-party-component/statelayout/compose_statelayout.md
    - 'Compose版SmartRefreshLayout': third-party-component/refreshlayout/compose_refreshlayout.md
  - 'API 文档':
    - '组件':
      - 'Text': api/elements/text.md
      - 'Button': api/elements/button.md
  - '开源项目':
    - 'Compose 仿豆瓣榜单客户端': open-source-project/compose-douban.md
    - 'Compose 实现月亮阴晴圆缺动画': open-source-project/compose-moon-animation.md
    - 'Compose 一款简易的音乐播放软件': open-source-project/compose-gmusic.md
    - 'Compose 伸缩 ToolBar 的实现': open-source-project/compose-scrollable-appbar.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Compose-Museum/Compose-Tutorial/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list

plugins:
  - search
  - macros
  - git-revision-date-localized:
      type: date
