site_name: Jetpack Compose 博物馆
repo_name: Jetpack Compose 博物馆
repo_url: https://github.com/Compose-Museum/Compose-Tutorial
site_url: https://github.com/Compose-Museum/Compose-Tutorial

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  feature:
    - tabs: true
    - instant
    - header.autohide

nav:
  - 'Jetpack Compose':
    - '概述': index.md